language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "3.9-dev"  # 3.9 development branch

script:
  - python -m unittest discover -s python_settings.tests
