# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
    example-workflow:
      jobs:
        - build_and_test: # this can be any name you choose
          executor: python/default
          steps:
            - checkout
            - run:
                name: Run tests
                command: python -m pytest
            - persist_to_workspace:
                root: ~/project
                paths:
                  - .