version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.8
      - test-3.9
      - test-3.10
      - test-3.11
      - test-3.12
      - test-3.13
jobs:
  test-3.7: &test-template
    docker:
      - image: cimg/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install pytest


      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd python_settings
            pytest -vvv tests

  test-3.6:
    <<: *test-template
    docker:
      - image: cimg/python:3.6

  test-3.8:
    <<: *test-template
    docker:
      - image: cimg/python:3.8
  
  test-3.9:
    <<: *test-template
    docker:
      - image: cimg/python:3.9

  test-3.10:
    <<: *test-template
    docker:
      - image: cimg/python:3.10

  test-3.11:
    <<: *test-template
    docker:
      - image: cimg/python:3.11

  test-3.12:
    <<: *test-template
    docker:
      - image: cimg/python:3.12

  test-3.13:
    <<: *test-template
    docker:
      - image: cimg/python:3.13
