version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install codecov
            pip install coverage
            pip install pytest


      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd python_settings
            coverage run -m pytest tests
            codecov

      # store artifacts (for example logs, binaries, etc)
      # to be available in the web app or through the API
      - store_artifacts:
          path: test-reports

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

#
## Python CircleCI 2.0 configuration file
##
## Check https://circleci.com/docs/2.0/language-python/ for more details
##
#jobs:
#    build:
#        docker:
#            # specify the version you desire here
#            # CircleCI maintains a library of pre-built images
#            # documented at https://circleci.com/docs/2.0/circleci-images/
#            - image: circleci/python:3.7
#
#        working_directory: ~/repo
#
#        steps:
#            - checkout
#
#            # Download and cache dependencies
#            - restore_cache:
#                keys:
#                    - v1-dependencies-{{ checksum "requirements.txt" }}
#                    # fallback to using the latest cache if no exact match is found
#                    - v1-dependencies-
#
#            - run:
#                name: install dependencies
#                command: |
#                    python3 -m venv venv
#                    . venv/bin/activate
#                    pip install -e .
#
#            - save_cache:
#                paths:
#                    - ./venv
#                key: v1-dependencies-{{ checksum "requirements.txt" }}
#
#            - run:
#                name: run tests
#                command: |
#                    . venv/bin/activate
#                    pip install codecov
#                    pip install coverage
#                    pip install opencv-python
#                    pip install pytest
#                    pip install scikit-image
#                    coverage run -m pytest tests
#                    codecov
#
#            # store artifacts (for example logs, binaries, etc)
#            # to be available in the web app or through the API
#            - store_artifacts:
#                path: test-reports